### ISSUE TITLE
Finish Preview Modal

### ISSUE THREAD

**Issue by dovy** [starterblocks/starterblocks#11]
- [x] Implement icons if had in ~/icons as seen here: https://github.com/starterblocks/starterblocks/blob/develop/src/modal-preview/SidebarContent.js#L98-L101
- [x] Finish off code for `requirements-list` as seen here: https://github.com/starterblocks/starterblocks/blob/develop/src/modal-preview/SidebarContent.js#L112-L141
- [x] Import dialog wizard has z-index issue. Can't click on any buttons.
- [x] Fix styling

**Comment by alfred-ta** [comment]
Let me know what else I should do for this task, I think it is OK to be closed.
