### ISSUE TITLE
Update Categories when Free/Pro clicked

### ISSUE THREAD

**Issue by dovy** [starterblocks/starterblocks#4]

**Comment by dovy** [comment]
Almost done! Two bugs:

- [x] All Sections should be updated to the total count within the Free/Pro. See: https://cloudup.com/cnHRrEKpkZy
- [x] If a category is selected with zero items, it shows all the items for the free/pro category. See: https://cloudup.com/c7UPryjRYUp

**Comment by alfred-ta** [comment]
Ready to be closed.
