### ISSUE TITLE
Persist items beyond page reload.

### ISSUE THREAD

**Issue by dovy** [starterblocks/starterblocks#5]
All/Free/Premium - Make this universal and persistent via cookie. So that they always have the same settings until the cookie expires. Make it easier for he user.

- [x] Free/All/Pro
- [X] Dependency Filters (IGNORE THIS, changed my mind)

**Comment by alfred-ta** [comment]
Is it allowed for me to use localStorage, @dovy ?

**Comment by dovy** [comment]
Anything you want.
