### ISSUE TITLE
None filter change

### ISSUE THREAD

**Issue by dovy** [starterblocks/starterblocks#60]
Only auto-select none when nothing is checked. Otherwise, filter as it was before. Someone pointed the mistake in the logic. My bad.

**Comment by dovy** [comment]
IE, if no items are selected, then show None. If all items are checked, add none.

**Comment by alfred-ta** [comment]
Not sure if there is any template that depends on default block and the other plugins block, should that be included when nothing is checked and none is auto-selected? Or excluded?

**Comment by dovy** [comment]
If all checkboxes checked: include none
If no checkboxes checked: include none
Else, don't include none.

**Comment by dovy** [comment]
Here's where it came up. If you check only on EditorsKit, you don't really want to see the "none" items. That's confusing. (From the author of EditorsKit)
